/**
 * generate-voice-variants.ts
 *
 * Offline script that reads src/data/interpretations.ts and produces
 * the 3 voice variants (sensible / mystique / pragmatique) per planet/sign
 * by calling Claude, then writes them to src/data/interpretations.generated.ts.
 *
 * Usage:
 *   ANTHROPIC_API_KEY=sk-... npx tsx scripts/generate-voice-variants.ts
 *
 * DO NOT run in CI — this hits the Anthropic API and costs real tokens.
 * Review the generated file manually (PY) before merging.
 *
 * Red lines for generation:
 *   - No deterministic predictions ("tu vas…", "you will…")
 *   - No moral judgments (good/bad, must/should)
 *   - No astro clichés ("chaque signe a ses forces")
 *   - Direct address (tu / you), body-anchored for sensible
 */

import Anthropic from "@anthropic-ai/sdk";
import { promises as fs } from "fs";
import path from "path";

const client = new Anthropic();

type VoiceKey = "sensible" | "mystique" | "pragmatique";

const VOICE_INSTRUCTIONS: Record<VoiceKey, string> = {
  sensible:
    "Ancre dans le corps et le ressenti. Adresse tendre, tutoie. Nomme les tensions, pas juste les qualités. Évite 'invite à', 'suggère', 'révèle'.",
  mystique:
    "Archétypes, symboles, images jungiennes. Évoque plus que tu ne définis. Mythe, rêve, profondeur. Reste incarné — jamais new-age flou.",
  pragmatique:
    "Concret, lucide, terre à terre. Zéro jargon ésotérique. Traduis en questions, en gestes, en décisions posables.",
};

const SYSTEM_TEMPLATE = (voice: VoiceKey) => `Tu réécris des interprétations astrologiques en voix ${voice}.

${VOICE_INSTRUCTIONS[voice]}

Règles dures :
- Tutoiement, toujours.
- Pas de prédictions ("tu vas…", "il t'arrivera…").
- Pas de phrases passe-partout.
- Conserver la précision astrologique (signe, planète, thème) mais l'intégrer dans la phrase, pas la lister.
- Longueur identique au texte original (±10 %).

Tu réponds UNIQUEMENT avec le texte réécrit, sans préambule, sans guillemets.`;

async function rewriteOne(text: string, voice: VoiceKey, key: string): Promise<string> {
  const response = await client.messages.create({
    model: "claude-sonnet-4-5",
    max_tokens: 800,
    system: SYSTEM_TEMPLATE(voice),
    messages: [
      {
        role: "user",
        content: `Réécris ce texte (${key}) en voix ${voice} :\n\n${text}`,
      },
    ],
  });
  const block = response.content[0];
  if (block.type !== "text") throw new Error("Unexpected response type");
  return block.text.trim();
}

async function main() {
  const srcPath = path.resolve("src/data/interpretations.ts");
  const outPath = path.resolve("src/data/interpretations.generated.ts");

  const src = await fs.readFile(srcPath, "utf-8");
  const srcModule = (await import(srcPath)) as {
    planetInSign: Record<string, Record<string, string>>;
  };

  const variants: Record<VoiceKey, { planetInSign: Record<string, Record<string, string>> }> = {
    sensible: { planetInSign: {} },
    mystique: { planetInSign: {} },
    pragmatique: { planetInSign: {} },
  };

  const voices: VoiceKey[] = ["sensible", "mystique", "pragmatique"];
  const planets = Object.keys(srcModule.planetInSign);

  for (const voice of voices) {
    for (const planet of planets) {
      variants[voice].planetInSign[planet] = {};
      const signs = Object.keys(srcModule.planetInSign[planet]);
      for (const sign of signs) {
        const base = srcModule.planetInSign[planet][sign];
        const key = `${planet}/${sign}`;
        process.stdout.write(`[${voice}] ${key}... `);
        try {
          const rewritten = await rewriteOne(base, voice, key);
          variants[voice].planetInSign[planet][sign] = rewritten;
          process.stdout.write("ok\n");
        } catch (err) {
          process.stdout.write(`FAIL: ${(err as Error).message}\n`);
          variants[voice].planetInSign[planet][sign] = base; // keep base as fallback
        }
      }
    }
  }

  const header = `// AUTO-GENERATED by scripts/generate-voice-variants.ts
// DO NOT EDIT BY HAND — regenerate with the script.
// Review each voice variant before merging; red lines documented in the script.

`;

  const body = `export const variants = ${JSON.stringify(variants, null, 2)} as const;\n`;

  await fs.writeFile(outPath, header + body, "utf-8");
  console.log(`\nWrote ${outPath}. Source: ${src.length} chars.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
